#!/usr/bin/env node
/**
 * Regenerates the keyboard-map table in README.md from src/keyboard/shortcuts.ts.
 *
 * The registry is already the single source of truth for every tooltip and for
 * the in-app overlay (shortcuts.ts, PLAN §8.10). A README that retypes those
 * bindings is a fourth copy that nothing checks, and it will be wrong within a
 * week. So it is generated, and `--check` fails the build when it drifts.
 *
 * The parse is deliberately literal: it reads the `SHORTCUTS` array's object
 * literals with a regex rather than importing the module, because shortcuts.ts
 * imports getEditorAPI, which reaches for `window`. A build script has no
 * business booting a renderer to print a table.
 *
 * Usage:
 *   node scripts/gen-keymap.mjs            # rewrite the block in README.md
 *   node scripts/gen-keymap.mjs --check    # exit 1 if README.md is out of date
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const SOURCE = path.join(ROOT, 'src', 'keyboard', 'shortcuts.ts');
const README = path.join(ROOT, 'README.md');

const BEGIN = '<!-- BEGIN KEYMAP: generated by scripts/gen-keymap.mjs — do not edit -->';
const END = '<!-- END KEYMAP -->';

const check = process.argv.includes('--check');

/* ------------------------------------------------------------------- parse */

const src = readFileSync(SOURCE, 'utf8');

const arrayStart = src.indexOf('export const SHORTCUTS');
if (arrayStart === -1) throw new Error('gen-keymap: SHORTCUTS not found in shortcuts.ts');
const arrayEnd = src.indexOf('\n];', arrayStart);
if (arrayEnd === -1) throw new Error('gen-keymap: could not find the end of SHORTCUTS');
const body = src.slice(arrayStart, arrayEnd);

const rows = [];
for (const m of body.matchAll(/\{\s*id:\s*'([^']+)',\s*keys:\s*\[([^\]]*)\],\s*label:\s*'([^']+)',\s*scope:\s*'([^']+)'/g)) {
  const [, id, keysRaw, label, scope] = m;
  const keys = [...keysRaw.matchAll(/'([^']*)'/g)].map((k) => k[1]);
  rows.push({ id, keys, label, scope });
}
if (rows.length === 0) throw new Error('gen-keymap: parsed zero shortcuts — the literal shape changed');

/** SCOPE_LABEL, read from the same file so the section headings cannot drift either. */
const scopeLabels = {};
{
  const block = /SCOPE_LABEL[^=]*=\s*\{([^}]*)\}/.exec(src);
  if (!block) throw new Error('gen-keymap: SCOPE_LABEL not found');
  for (const m of block[1].matchAll(/(\w+):\s*'([^']+)'/g)) scopeLabels[m[1]] = m[2];
}

const scopeOrder = (() => {
  const block = /SCOPE_ORDER[^=]*=\s*\[([^\]]*)\]/.exec(src);
  if (!block) throw new Error('gen-keymap: SCOPE_ORDER not found');
  return [...block[1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
})();

/* ------------------------------------------------------------------ render */

// Windows/Linux naming. `Ctrl` is the platform accelerator and renders as Cmd on
// macOS in the app itself; this project ships a Windows build, so the README
// says Ctrl and says so once, above the table.
const GLYPH = { ArrowLeft: 'Left', ArrowRight: 'Right', ArrowUp: 'Up', ArrowDown: 'Down' };
const key = (combo) => combo.split('+').map((p) => GLYPH[p] ?? p).join('+');
const keys = (list) => list.map((c) => `\`${key(c)}\``).join(' or ');

const lines = [];
for (const scope of scopeOrder) {
  const inScope = rows.filter((r) => r.scope === scope);
  if (inScope.length === 0) continue;
  lines.push(`**${scopeLabels[scope] ?? scope}**`, '', '| Keys | Action |', '| --- | --- |');
  for (const r of inScope) lines.push(`| ${keys(r.keys)} | ${r.label} |`);
  lines.push('');
}

const generated = `${BEGIN}\n\n${lines.join('\n').trimEnd()}\n\n${END}`;

/* ------------------------------------------------------------------- write */

let readme;
try {
  readme = readFileSync(README, 'utf8');
} catch {
  console.error('gen-keymap: README.md not found');
  process.exit(1);
}

const from = readme.indexOf(BEGIN);
const to = readme.indexOf(END);
if (from === -1 || to === -1 || to < from) {
  console.error(`gen-keymap: README.md has no keymap block. Insert these two lines where the table belongs:\n${BEGIN}\n${END}`);
  process.exit(1);
}

const next = readme.slice(0, from) + generated + readme.slice(to + END.length);

if (next === readme) {
  console.log(`gen-keymap: README.md is up to date (${rows.length} shortcuts)`);
  process.exit(0);
}

if (check) {
  console.error('gen-keymap: README.md keyboard map is out of date — run `npm run readme:keymap`');
  process.exit(1);
}

writeFileSync(README, next);
console.log(`gen-keymap: README.md keyboard map rewritten (${rows.length} shortcuts)`);
